global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: trading-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - unified-trading-service:9464

  - job_name: risk-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - risk-api:8090
