alert_threshold_critical: 0.9
alert_threshold_warning: 0.75
atr_multiplier: 2.0
atr_period: 14
default_risk_per_trade: 0.02
default_stop_loss_distance: 0.05
emergency_stop_daily_loss_threshold: 0.1
emergency_stop_drawdown_threshold: 0.25
emergency_stop_var_threshold: 0.2
enable_backtesting_validation: true
enable_emergency_stop: true
enable_ml_risk_models: false
enable_regime_detection: false
enable_risk_alerts: true
enable_stress_testing: true
enable_trailing_stops: true
kelly_fraction_multiplier: 0.5
max_correlation_exposure: 0.6
max_correlation_threshold: 0.7
max_daily_loss: 0.05
max_drawdown: 0.15
max_illiquid_exposure: 0.2
max_portfolio_exposure: 0.95
max_portfolio_var_95: 0.1
max_portfolio_volatility: 0.3
max_position_size: 0.2
max_positions: 10
max_sector_concentration: 0.4
max_single_stock_concentration: 0.15
max_stop_loss_distance: 0.2
min_backtesting_period: 252
min_backtesting_sharpe: 0.5
min_liquidity_score: 0.3
min_position_size: 0.001
min_stop_loss_distance: 0.005
position_sizing_method: volatility_adjusted
risk_monitoring_frequency: 30
stop_loss_method: atr_based
stress_test_scenarios:
  interest_rate_shock: -0.1
  market_crash: -0.2
  sector_rotation: -0.15
  volatility_spike: 2.0
target_portfolio_volatility: 0.15
trailing_activation_threshold: 0.035
trailing_stop_distance: 0.03
trailing_stop_method: percentage
use_atr_position_sizing: true
use_atr_stop_loss: true
var_calculation_method: historical
var_lookback_period: 252
