# Alpaca Trading Bot Configuration

# General Settings
start_date: "10 days ago"
end_date: "1 Jan, 2023"
timeframe: "1Min"
candle_lookback_period: 2
investment_amount: 10000
max_trades_active: 10
trade_capital_percent: 5
stop_loss: 0.2
trailing_stop: 0.2
activate_trailing_stop_loss_at: 0.1
limit_price: 0.5
exchange: "CBSE"
sleep_time_between_trades: 60
extended_hours: true
strategy: "StochRSI"

# Indicators
indicators:
  stochRSI:
    enabled: true
    lower_band: 35
    upper_band: 100
    K: 3
    D: 3
    rsi_length: 14
    stoch_length: 14
    source: "Close"
    # Dynamic band adjustment settings
    dynamic_bands_enabled: true
    atr_period: 20
    atr_sensitivity: 1.5
    band_adjustment_factor: 0.3
    min_band_width: 10
    max_band_width: 50
  stoch:
    enabled: true
    lower_band: 35
    upper_band: 80
    K_Length: 14
    smooth_K: 3
    smooth_D: 3
  EMA:
    enabled: true
    ema_period: 9
    fast_period: 10
    slow_period: 30
    source: "Close"
    smoothing: 2

# Risk Management
risk_management:
  use_atr_stop_loss: true
  atr_period: 14
  atr_multiplier: 2.0
  use_atr_position_sizing: true

# Volume Confirmation
volume_confirmation:
  enabled: true
  volume_period: 20
  relative_volume_period: 50
  volume_confirmation_threshold: 1.2
  min_volume_ratio: 1.0
  profile_periods: 100
  require_volume_confirmation: true
