# Performance Configuration for Trading Bot Application
performance:
  # Caching configuration
  caching:
    redis_url: null  # Set to Redis URL if available (e.g., redis://localhost:6379/0)
    enable_compression: true
    local_cache_size: 10000
    default_ttl: 300  # 5 minutes
    realtime_ttl: 10  # 10 seconds
    static_ttl: 3600  # 1 hour
  
  # Database optimization
  database:
    connection_pool_size: 20
    connection_timeout: 30
    query_cache_size: 1000
    enable_query_optimization: true
    batch_size: 100
  
  # HTTP/API configuration
  http:
    max_connections: 100
    max_connections_per_host: 20
    connection_timeout: 30
    request_timeout: 30
    max_retries: 3
    backoff_factor: 1.0
    enable_compression: true
  
  # Rate limiting
  rate_limiting:
    requests_per_second: 10.0
    burst_size: 20
    window_size: 60.0
    enable_per_endpoint_limits: true
  
  # WebSocket optimization
  websocket:
    compression: true
    buffer_size: 65536  # 64KB
    ping_interval: 25
    ping_timeout: 60
    max_message_queue: 10000
    reconnect_interval: 5.0
    max_reconnect_attempts: 10
  
  # Threading and async
  threading:
    api_pool_workers: 20
    data_processing_workers: 10
    background_workers: 5
    max_concurrent_requests: 50
  
  # Memory management
  memory:
    enable_gc_optimization: true
    gc_threshold_0: 700
    gc_threshold_1: 10
    gc_threshold_2: 10
    max_memory_usage_mb: 2048  # 2GB limit
    cleanup_interval: 300  # 5 minutes
  
  # Monitoring and profiling
  monitoring:
    enable_performance_tracking: true
    enable_memory_profiling: false  # Enable for debugging only
    enable_request_profiling: false  # Enable for debugging only
    stats_retention_count: 10000
    performance_log_interval: 60  # Log stats every minute
  
  # Data fetching optimization
  data_fetching:
    enable_batching: true
    batch_timeout: 1.0  # Max wait for batch completion
    max_batch_size: 100
    enable_streaming: true
    stream_buffer_size: 1000
  
  # Response optimization
  response:
    enable_etag_caching: true
    enable_gzip_compression: true
    gzip_compression_threshold: 1024  # Compress responses > 1KB
    compression_level: 6  # Balance between speed and compression ratio
    json_separators: [',', ':']  # Compact JSON output
    float_precision: 4  # Round floats to 4 decimal places
  
  # Circuit breaker configuration
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 60.0
    half_open_max_calls: 3
  
  # Development vs Production settings
  development:
    enable_debug_logging: false
    enable_request_logging: true
    enable_performance_warnings: true
    cache_ttl_multiplier: 0.1  # Shorter cache times for development
  
  production:
    enable_debug_logging: false
    enable_request_logging: false
    enable_performance_warnings: false
    cache_ttl_multiplier: 1.0
    enable_aggressive_caching: true
    enable_connection_pooling: true