activate_trailing_stop_loss_at: 0.1
api:
  alpaca_auth_file: AUTH/authAlpaca.txt
  rate_limit_requests: 200
  rate_limit_window: 60
  request_timeout: 30
  retry_attempts: 3
  retry_delay: 1.0
candle_lookback_period: 2
database:
  max_overflow: 20
  pool_recycle: 3600
  pool_size: 10
  pool_timeout: 30
  url: sqlite:///database/trading_data.db
end_date: 1 Jan, 2023
exchange: CBSE
extended_hours: true
indicators:
  EMA:
    ema_period: 9
    enabled: true
    fast_period: 10
    slow_period: 30
    smoothing: 2
    source: Close
  stoch:
    K_Length: 14
    enabled: true
    lower_band: 35
    smooth_D: 3
    smooth_K: 3
    upper_band: 80
  stochRSI:
    D: 3
    K: 3
    enabled: true
    lower_band: 35
    rsi_length: 14
    source: Close
    stoch_length: 14
    upper_band: 100
investment_amount: 10000
limit_price: 0.5
logging:
  backup_count: 5
  file_path: logs/trading_bot.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_bytes: 10485760
max_trades_active: 10
risk_management:
  atr_multiplier: 2.0
  atr_period: 14
  max_daily_loss: 0.05
  max_drawdown: 0.15
  max_position_size: 0.1
  use_atr_position_sizing: true
  use_atr_stop_loss: true
sleep_time_between_trades: 60
start_date: 10 days ago
stop_loss: 0.2
strategy: StochRSI
timeframe: 1Min
trade_capital_percent: 5
trailing_stop: 0.2
