activate_trailing_stop_loss_at: 0.015
api:
  alpaca_auth_file: AUTH/authAlpaca.txt
  rate_limit_requests: 300
  rate_limit_window: 60
  request_timeout: 10
  retry_attempts: 2
  retry_delay: 0.5
candle_lookback_period: 50
crypto_only: true
database:
  max_overflow: 10
  pool_recycle: 1800
  pool_size: 5
  pool_timeout: 15
  url: sqlite:///database/crypto_trading.db
end_date: 1 Jan, 2023
exchange: CBSE
extended_hours: false
indicators:
  EMA:
    ema_period: 5
    enabled: true
    fast_period: 5
    slow_period: 13
    smoothing: 2
    source: Close
  stoch:
    K_Length: 9
    enabled: true
    lower_band: 35
    smooth_D: 2
    smooth_K: 2
    upper_band: 65
  stochRSI:
    D: 3
    K: 3
    atr_period: 10
    dynamic_bands_enabled: false
    enabled: true
    lower_band: 35
    rsi_length: 9
    source: Close
    stoch_length: 9
    upper_band: 65
investment_amount: 10000
limit_price: 0.5
logging:
  backup_count: 5
  file_path: logs/crypto_scalping.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_bytes: 10485760
market_type: crypto
max_trades_active: 15
risk_management:
  atr_multiplier: 1.5
  atr_period: 10
  max_daily_loss: 0.08
  max_drawdown: 0.2
  max_position_size: 0.15
  use_atr_position_sizing: true
  use_atr_stop_loss: true
signal_filters:
  confirmation_threshold: 1.2
  confirmation_window: 3
  enable_relative_volume: true
  enabled: true
  min_signal_gap_seconds: 300
  minimum_quality_score: 0.6
  relative_volume_threshold: 1.5
  require_confirmation: true
  require_volume_confirmation: true
  volume_ma_period: 20
  volume_strength_levels:
    high: 1.0
    low: -1.0
    normal: 0.0
    very_high: 2.0
    very_low: -2.0
  volume_trend_periods: 5
sleep_time_between_trades: 1
start_date: 1 day ago
stop_loss: 0.015
strategy: crypto_scalping
symbols:
- BTC/USD
- ETH/USD
timeframe: 1Min
trade_capital_percent: 3
trailing_stop: 0.01
